version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: collab_postgres
    restart: always
    environment:
      POSTGRES_USER: collab_user
      POSTGRES_PASSWORD: collab_pass
      POSTGRES_DB: collab_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
